name: on-commit-test
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest
        env:
            NODE_OPTIONS: --experimental-modules
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup node version
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Installing project dependencies
              run: npm install
            - name: Test the code
              run: npm start test
              env:
                  CI: true
