name: on-commit-test
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup node version
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
              env:
                  HUSKY: 0
            - name: Installing project dependencies
              run: npm install
            - name: Linting the code
              run: npm start lint
